services:
  pastebox:
    build: .
    image: pastebox:latest
    container_name: pastebox
    restart: unless-stopped
    ports:
      - "8080:8080"
    # NOTE: The default time zone is Asia/Seoul (GMT +9). Change it as needed.
    #environment:
    #  TZ: "Asia/Seoul"
    volumes:
      - ./data:/paste-data
